### ISSUE TITLE
Abilitity to take polygon input and clip the raster on that 

### ISSUE THREAD

**Issue by ArpitKubadia** [opendatacube/datacube-wps#90]
The user should be able to submit a polygon input like here - https://www.sentinel-hub.com/faq/how-can-i-clip-image-specific-polygon/
The output image should be an intersection of the `bbox` and the `geometry`.

**Comment by uchchwhash** [comment]
Hi @ArpitKubadia,
A bit confused here. Our WPS processes (pixel drills and polygon drills) produce a timeseries from a polygon or a point, and does not produce imagery. Also, it does the clipping on the input images for polygon drills like so: https://github.com/opendatacube/datacube-wps/blob/master/datacube_wps/processes/__init__.py#L449 because we want to limit the statistics to the geometry provided.
I think what you are asking for can be achieved with `Datacube.load` in conjunction with the `geometry_mask` defined in that file.
Please let us know if that's what you were after! 😄

**Comment by ArpitKubadia** [comment]
That wasn't quite what I was asking for, but it helped. My idea was more about taking a polygon input in the WMS request and then clipping the image based on the polygon. I have written a custom function in my fork for this. Thanks!

**Comment by benjimin** [comment]
@ArpitKubadia I couldn't find your fork of this repo, so I'm assuming this issue may have been intended for a different repo (this one is only for WPS, whereas WMS is handled by the [OWS-titled](https://github.com/opendatacube/datacube-ows) repo).

Also, I'm thinking that clipping a raster to a polygon might already be implemented on the client side:
https://openlayers.org/en/latest/examples/layer-clipping.html
